language: python
python:
  - "3.6"

install:
  - sudo apt-get update
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n CIRI-long python=3.6
  - conda activate CIRI-long
  - travis_retry pip install -r requirements.txt
  - python setup.py install
  - wget https://github.com/bioinfo-biols/CIRI-long/releases/download/v1.0/CIRI-long_test_data_v2.tar.gz
  - tar zxvf CIRI-long_test_data_v2.tar.gz

script:
  - CIRI-long --version
  - python3 setup.py build_ext --inplace
  - python3 setup.py test
  - cd test_data
  - CIRI-long call -i test_reads.fa -o ./test_call -r mm10_chr12.fa -p test -a mm10_chr12.gtf -t 2
  - echo "test ./test_call/test.cand_circ.fa" > ./test.list
  - CIRI-long collapse -i ./test.list -o test_collapse -r mm10_chr12.fa -p test -a mm10_chr12.gtf -t 2

notifications:
  pushover:
    api_key: ${API_TOKEN}
    users:
      - ${USER_KEY}

