language: python
python:
  - "3.6"

install:
  - sudo apt-get update
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n CIRI-long python=3.6
  - conda activate CIRI-long
  - travis_retry pip install -r requirements.txt
  - python setup.py install

script:
  - CIRI-long --version
  - python3 setup.py build_ext --inplace
	- python3 setup.py test

notifications:
  pushover:
    api_key: ${API_TOKEN}
    users:
      - ${USER_KEY}

