language: python
python:
  - "3.8"

install:
  - make all

script:
  - CIRI-long --version
  - make test

notifications:
  pushover:
    api_key: ${API_TOKEN}
    users:
      - ${USER_KEY}